import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import State from 'App/Models/State'
import Country from 'App/Models/Country'
import Region from 'App/Models/Region'
import RegionEnum from 'Contracts/enums/Region'

export default class StateSeeder extends BaseSeeder {
  public async run() {
    const countryBr = await Country.findByOrFail('abbreviation', 'BR')
    const regions = await Region.all()

    await State.createMany([
      {
        name: 'Acre',
        uf: 'AC',
        ibge: 12,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[68]',
      },
      {
        name: 'Alagoas',
        uf: 'AL',
        ibge: 27,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[82]',
      },
      {
        name: 'Amazonas',
        uf: 'AM',
        ibge: 13,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[97,92]',
      },
      {
        name: 'Amapá',
        uf: 'AP',
        ibge: 16,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[96]',
      },
      {
        name: 'Bahia',
        uf: 'BA',
        ibge: 29,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[77,75,73,74,71]',
      },
      {
        name: 'Ceará',
        uf: 'CE',
        ibge: 23,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[88,85]',
      },
      {
        name: 'Distrito Federal',
        uf: 'DF',
        ibge: 53,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.CENTRO_OESTE)?.id,
        ddd: '[61]',
      },
      {
        name: 'Espírito Santo',
        uf: 'ES',
        ibge: 32,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUDESTE)?.id,
        ddd: '[28,27]',
      },
      {
        name: 'Goiás',
        uf: 'GO',
        ibge: 52,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.CENTRO_OESTE)?.id,
        ddd: '[62,64,61]',
      },
      {
        name: 'Maranhão',
        uf: 'MA',
        ibge: 21,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[99,98]',
      },
      {
        name: 'Minas Gerais',
        uf: 'MG',
        ibge: 31,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUDESTE)?.id,
        ddd: '[34,37,31,33,35,38,32]',
      },
      {
        name: 'Mato Grosso do Sul',
        uf: 'MS',
        ibge: 50,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.CENTRO_OESTE)?.id,
        ddd: '[67]',
      },
      {
        name: 'Mato Grosso',
        uf: 'MT',
        ibge: 51,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.CENTRO_OESTE)?.id,
        ddd: '[65,66]',
      },
      {
        name: 'Pará',
        uf: 'PA',
        ibge: 15,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[91,94,93]',
      },
      {
        name: 'Paraíba',
        uf: 'PB',
        ibge: 25,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[83]',
      },
      {
        name: 'Pernambuco',
        uf: 'PE',
        ibge: 26,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[81,87]',
      },
      {
        name: 'Piauí',
        uf: 'PI',
        ibge: 22,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[89,86]',
      },
      {
        name: 'Paraná',
        uf: 'PR',
        ibge: 41,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUL)?.id,
        ddd: '[43,41,42,44,45,46]',
      },
      {
        name: 'Rio de Janeiro',
        uf: 'RJ',
        ibge: 33,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUDESTE)?.id,
        ddd: '[24,22,21]',
      },
      {
        name: 'Rio Grande do Norte',
        uf: 'RN',
        ibge: 24,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[84]',
      },
      {
        name: 'Rondônia',
        uf: 'RO',
        ibge: 11,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[69]',
      },
      {
        name: 'Roraima',
        uf: 'RR',
        ibge: 14,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[95]',
      },
      {
        name: 'Rio Grande do Sul',
        uf: 'RS',
        ibge: 43,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUL)?.id,
        ddd: '[53,54,55,51]',
      },
      {
        name: 'Santa Catarina',
        uf: 'SC',
        ibge: 42,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUL)?.id,
        ddd: '[47,48,49]',
      },
      {
        name: 'Sergipe',
        uf: 'SE',
        ibge: 28,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORDESTE)?.id,
        ddd: '[79]',
      },
      {
        name: 'São Paulo',
        uf: 'SP',
        ibge: 35,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.SUDESTE)?.id,
        ddd: '[11,12,13,14,15,16,17,18,19]',
      },
      {
        name: 'Tocantins',
        uf: 'TO',
        ibge: 17,
        countryId: countryBr.id,
        regionId: regions.find((region) => region.abbreviation === RegionEnum.NORTE)?.id,
        ddd: '[63]',
      },
      {
        name: 'Exterior',
        uf: 'EX',
        ibge: 99,
        countryId: null,
        regionId: null,
        ddd: null,
      },
    ])
  }
}
